### ISSUE TITLE
[✨ feature]  Use the new design for github issue search input

### ISSUE THREAD

**Issue by Fredkiss3** [Fredkiss3/gh-next#60]
## Is your feature request related to a problem? Please describe.

Use this design :

<img width="624" alt="image" src="https://github.com/Fredkiss3/gh-next/assets/38298743/633ceb74-6fab-48fd-a705-faca3534f167">

![Image](https://github.com/Fredkiss3/gh-next/assets/38298743/f088b930-6c09-4f2d-b568-c2b3b85e8a06)

## Additional context

Check if it can be done with `<div contenteditable="true" />` thouh github doesn't use this (how ?)
It is using `position:absolute` and aligned with an input with a transparent text color : 
<img width="1419" alt="Capture d’écran 2023-09-21 à 16 26 01" src="https://github.com/Fredkiss3/gh-next/assets/38298743/fe1a4462-f380-4769-9324-f2a2e0f112f6">

```css
.tokens {
  position: absolute;
  user-select: none;
  white-space: nowrap;
  word-break: break-word;
  font-size: 14px;
  flex: 1 1 0%;
  width: 100%;
  padding: 0px;
  top: 50%;
  transform: translateY(-50%);
}

.input {
  color: transparent;
  font-family: inherit;
  border: 0px;
  padding: 0px;
  box-shadow: none;
  display: flex;
  width: 100%;
  position: relative;
  resize: none;
  outline: none;
  background: transparent;
  overflow: auto hidden;
  min-width: 100%;
  caret-color: rgb(230, 237, 243);
  font-size: 14px;
  flex: 1 1 0%;
  height: 100%;
  max-height: unset;
}
```

- [x] Are you willing to make a PR for this ?
